apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlozaG5OVEV6T21jek1ISm5NMmN6TUhKSE13PT0iCgkJfQoJfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace:  test
type: kubernetes.io/dockerconfigjson