apiVersion: v1
kind: Service
metadata:
  name: httpd-service-webserver
  namespace: test
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004